package ui;

import java.util.ArrayList;
import java.util.Enumeration;
import javax.swing.DefaultListModel;
import javax.swing.JDialog;

/**
 * This dialog displays a list of template logs available for the selected
 * server
 *
 * @author cartin
 */
public class LogFileChooser extends javax.swing.JDialog
{

    /**
     * Creates new form LogFileChooser
     * @param parent
     * @param modal
     * @param logList
     */
    public LogFileChooser(JDialog parent, boolean modal, DefaultListModel logList, DefaultListModel selectedList)
    {
	super(parent, modal);
	initComponents();
	
	this.logList = new DefaultListModel();
	
	Enumeration<String> list = logList.elements();
	while(list.hasMoreElements())
	{
	    String s = list.nextElement();
	    if(!selectedList.contains(s))
		this.logList.addElement(s);
	}
	
	jListAvailableLogFiles.setModel(this.logList);
	
	logSelected = new ArrayList<>();
	
	setLocationRelativeTo(parent);
    }

    public ArrayList<String> showDialog()
    {
	setVisible(true);
	
	return logSelected;
    }
    
    /**
     * This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jPanelRoot = new javax.swing.JPanel();
        jButtonCancel = new javax.swing.JButton();
        jButtonSelect = new javax.swing.JButton();
        jScrollPaneAvailableLogFiles = new javax.swing.JScrollPane();
        jListAvailableLogFiles = new javax.swing.JList();
        jLabelDescription = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Add Log File");
        setMinimumSize(new java.awt.Dimension(180, 352));
        setModal(true);

        jButtonCancel.setText("Cancel");
        jButtonCancel.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButtonCancelActionPerformed(evt);
            }
        });

        jButtonSelect.setText("Select");
        jButtonSelect.setEnabled(false);
        jButtonSelect.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButtonSelectActionPerformed(evt);
            }
        });

        jListAvailableLogFiles.setToolTipText("This list contains the log file profiles defined in the \"Template Log Files\" tab of the Preferences window.");
        jListAvailableLogFiles.addListSelectionListener(new javax.swing.event.ListSelectionListener()
        {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt)
            {
                jListAvailableLogFilesValueChanged(evt);
            }
        });
        jScrollPaneAvailableLogFiles.setViewportView(jListAvailableLogFiles);

        jLabelDescription.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelDescription.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelDescription.setText("Template log files to add:");
        jLabelDescription.setFocusable(false);

        javax.swing.GroupLayout jPanelRootLayout = new javax.swing.GroupLayout(jPanelRoot);
        jPanelRoot.setLayout(jPanelRootLayout);
        jPanelRootLayout.setHorizontalGroup(
            jPanelRootLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRootLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelRootLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelRootLayout.createSequentialGroup()
                        .addComponent(jButtonSelect, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                        .addComponent(jButtonCancel))
                    .addComponent(jScrollPaneAvailableLogFiles, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jLabelDescription, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanelRootLayout.setVerticalGroup(
            jPanelRootLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelRootLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelDescription)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPaneAvailableLogFiles, javax.swing.GroupLayout.DEFAULT_SIZE, 270, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelRootLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCancel)
                    .addComponent(jButtonSelect))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelRoot, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelRoot, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jListAvailableLogFilesValueChanged(javax.swing.event.ListSelectionEvent evt)//GEN-FIRST:event_jListAvailableLogFilesValueChanged
    {//GEN-HEADEREND:event_jListAvailableLogFilesValueChanged
        if(logList.isEmpty())
	{
	    jButtonSelect.setEnabled(false);
	}
	else
	{
	    jButtonSelect.setEnabled(true);
	    logSelected = new ArrayList<>(jListAvailableLogFiles.getSelectedValuesList());
	}
    }//GEN-LAST:event_jListAvailableLogFilesValueChanged

    private void jButtonSelectActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButtonSelectActionPerformed
    {//GEN-HEADEREND:event_jButtonSelectActionPerformed
        dispose();
    }//GEN-LAST:event_jButtonSelectActionPerformed

    private void jButtonCancelActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButtonCancelActionPerformed
    {//GEN-HEADEREND:event_jButtonCancelActionPerformed
        dispose();
    }//GEN-LAST:event_jButtonCancelActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancel;
    private javax.swing.JButton jButtonSelect;
    private javax.swing.JLabel jLabelDescription;
    private javax.swing.JList jListAvailableLogFiles;
    private javax.swing.JPanel jPanelRoot;
    private javax.swing.JScrollPane jScrollPaneAvailableLogFiles;
    // End of variables declaration//GEN-END:variables

    private DefaultListModel logList;
    private ArrayList<String> logSelected;
}
